### ISSUE TITLE
Error with node_attributes in env_variable_switches

### ISSUE THREAD

**Issue by JohnBernas** [mkocher/soloist#36]
When I try to use `node_attributes` in `env_variable_switches`, like this:

```
recipes:
- sprout-git::git_projects

node_attributes:
  git_projects:
    -
      - repo1
      - https://github.com/me/repo1.git

env_variable_switches:
  PROJECT:
    p2:
      node_attributes:
        git_projects:
          -
            - repo2
            - https://github.com/me/repo2.git
```

I get the following error:

```
/Users/joao/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/soloist-1.0.3/lib/soloist/royal_crown.rb:75:in `+': no implicit conversion of nil into Array (TypeError)
    from /Users/joao/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/soloist-1.0.3/lib/soloist/royal_crown.rb:75:in `merge_array_property'
    from /Users/joao/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/soloist-1.0.3/lib/soloist/royal_crown.rb:30:in `merge_cookbook_paths'
    from /Users/joao/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/soloist-1.0.3/lib/soloist/royal_crown.rb:19:in `merge!'
    from /Users/joao/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/soloist-1.0.3/lib/soloist/config.rb:81:in `block (3 levels) in compiled'
    from /Users/joao/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/soloist-1.0.3/lib/soloist/config.rb:80:in `each'
    from /Users/joao/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/soloist-1.0.3/lib/soloist/config.rb:80:in `block (2 levels) in compiled'
    from /Users/joao/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/soloist-1.0.3/lib/soloist/config.rb:79:in `each'
    from /Users/joao/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/soloist-1.0.3/lib/soloist/config.rb:79:in `block in compiled'
    from /Users/joao/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/soloist-1.0.3/lib/soloist/config.rb:77:in `tap'
    from /Users/joao/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/soloist-1.0.3/lib/soloist/config.rb:77:in `compiled'
    from /Users/joao/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/soloist-1.0.3/lib/soloist/config.rb:46:in `cookbook_paths'
```

I've noticed an old issue that mentions this error, but it has been closed for half a year now...
